-- --------------------------------------------------------
-- 主机:                           127.0.0.1
-- 服务器版本:                        5.5.5-10.1.30-MariaDB - mariadb.org binary distribution
-- 服务器操作系统:                      Win32
-- HeidiSQL 版本:                  8.3.0.4694
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 导出 adskeywordtextdb 的数据库结构
CREATE DATABASE IF NOT EXISTS `adskeywordtextdb` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `adskeywordtextdb`;


-- 导出  表 adskeywordtextdb.keywordtexts 结构
CREATE TABLE IF NOT EXISTS `keywordtexts` (
  `id` int(32) NOT NULL AUTO_INCREMENT,
  `url` varchar(256) NOT NULL,
  `keyword` varchar(50) DEFAULT NULL,
  `title` varchar(256) DEFAULT NULL,
  `article` text,
  `summary` text,
  PRIMARY KEY (`id`),
  KEY `uniq_index` (`url`,`keyword`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- 数据导出被取消选择。


-- 导出  表 adskeywordtextdb.query_words 结构
CREATE TABLE IF NOT EXISTS `query_words` (
  `id` int(32) NOT NULL,
  `keyword` varchar(50) NOT NULL,
  `flags` int(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `query_words` (`id`, `keyword`, `flags`) VALUES
	(1, '0 apr balance transfer', 0),
	(2, '0 balance transfer', 0),
	(3, '0 balance transfer credit cards'， 0),
	(4, '0 interest credit card balance transfer'， 0),
	(5, '1 800 business number'， 0),
	(6, '24 hour plumber service'， 0),
	(7, '401k'， 0),
	(8, '401k for small business'， 0),
	(9, '401k gold ira rollover'， 0),
	(10, '401k gold ira rollovers'， 0),
	(11, '401k investment strategies'， 0),
	(12, '401k ira'， 0),
	(13, '401k retirement plan'， 0),
	(14, '401k rollover ira'， 0),
	(15, '401k rollover to ira'， 0),
	(16, '401k to gold ira rollover'， 0),
	(17, '402k gold ira rollover'， 0),
	(18, '800 business number'， 0),
	(19, '800 number business'， 0),
	(20, '800 number for business'， 0),
	(21, '800 numbers business'， 0),
	(22, '800 numbers for business'， 0),
	(23, 'a fib stroke'， 0),
	(24, 'a	online rn bsncash advance business loans'， 0),
	(25, 'a1 c level'， 0),
	(26, 'a1c'， 0),
	(27, 'aacsb online accounting'， 0),
	(28, 'aarp burial insurance'， 0),
	(29, 'aarp life insurance'， 0),
	(30, 'aarp medicare supplement insurance'， 0),
	(31, 'aarp medicare supplement plans'， 0),
	(32, 'aarp supplement health insurance'， 0),
	(33, 'aarp supplemental dental insurance'， 0),
	(34, 'accept credit card payments'， 0),
	(35, 'accept credit card small business'， 0),
	(36, 'accept credit cards small business'， 0),
	(37, 'accept online credit card payments'， 0),
	(38, 'accepted credit card small business'， 0),
	(39, 'accepted credit cards small business'， 0),
	(40, 'accepting credit card payments for small business'， 0),
	(41, 'accepting credit cards online for small business'， 0),
	(42, 'accepting credit cards small business'， 0),
	(43, 'accident auto lawyer'， 0),
	(44, 'accident lawyers'， 0),
	(45, 'account small business software'， 0),
	(46, 'account software small business'， 0),
	(47, 'accounting degree'， 0),
	(48, 'accounting degree online accredited'， 0),
	(49, 'accounting degree online programs'， 0),
	(50, 'accounting degrees online'， 0),
	(51, 'accounting online degree'， 0),
	(52, 'accounts receivable factoring company'， 0),
	(53, 'accredit cards processing small business'， 0),
	(54, 'accredited nursing schools online'， 0),
	(55, 'accredited online accounting degree'， 0),
	(56, 'accredited online college degree programs'， 0),
	(57, 'accredited online computer science degree'， 0),
	(58, 'accredited online degree'， 0),
	(59, 'accredited online mba programs'， 0),
	(60, 'accredited online nursing program'， 0),
	(61, 'accredited online psychology degree'， 0),
	(62, 'accredited rn programs online'， 0),
	(63, 'ach payment processing'， 0),
	(64, 'acid reflux'， 0),
	(65, 'acid reflux heartburn'， 0),
	(66, 'acid reflux remedy'， 0),
	(67, 'acid reflux treatment'， 0),
	(68, 'acne laser operation'， 0),
	(69, 'acne skin care products'， 0),
	(70, 'acne treatment'， 0),
	(71, 'acne treatment products'， 0),
	(72, 'acquired hemophilia a'， 0),
	(73, 'acredit card processing small business'， 0),
	(74, 'acredit cards processing small business'， 0),
	(75, 'acredited online colleges'， 0),
	(76, 'add adhd treatment'， 0),
	(77, 'add treatment'， 0),
	(78, 'addiction treatment'， 0),
	(79, 'adhd'， 0),
	(80, 'adhd drug'， 0),
	(81, 'adhd facts'， 0),
	(82, 'adhd info'， 0),
	(83, 'adhd information'， 0),
	(84, 'adhd symptoms'， 0),
	(85, 'adhd treatment'， 0),
	(86, 'adhd treatment for child'， 0),
	(87, 'adhd treatment options'， 0),
	(88, 'adhd treatments'， 0),
	(89, 'adult adhd medications'， 0),
	(90, 'advanced bladder cancer treatment'， 0),
	(91, 'advanced breast cancer'， 0),
	(92, 'advanced breast cancer treatments'， 0),
	(93, 'advanced colon cancer treatment'， 0),
	(94, 'advanced colorectal cancer'， 0),
	(95, 'advanced colorectal cancer treatment'， 0),
	(96, 'advanced copd treatment'， 0),
	(97, 'advanced kidney cancer  treatment'， 0),
	(98, 'advanced kidney cancer symptoms'， 0),
	(99, 'advanced kidney cancer treatment'， 0),
	(100, 'advanced kidney cancer treatments'， 0),
	(101, 'advanced liver cancer'， 0),
	(102, 'advanced liver cancer treatment'， 0),
	(103, 'advanced lung cancer treatment'， 0),
	(104, 'advanced lung cancer treatments'， 0),
	(105, 'advanced matastatic breast cancer treatment'， 0),
	(106, 'advanced matastatic breast cancer treatments'， 0),
	(107, 'advanced matastatic colon cancer treatment'， 0),
	(108, 'advanced matastatic kidney cancer treatment'， 0),
	(109, 'advanced matastatic liver cancer treatment'， 0),
	(110, 'advanced matastatic pancreatic cancer treatment'， 0),
	(111, 'advanced melanoma'， 0),
	(112, 'advanced melanoma treatment'， 0),
	(113, 'advanced melanoma treatments'， 0),
	(114, 'advanced metastatic beast cancer treatment'， 0),
	(115, 'advanced metastatic bladder cancer treatment'， 0),
	(116, 'advanced metastatic breast cancer treatment'， 0),
	(117, 'advanced metastatic breast cancer treatments'， 0),
	(118, 'advanced metastatic colon cancer treatments'， 0),
	(119, 'advanced metastatic kidney cancer treatment'， 0),
	(120, 'advanced metastatic kidney cancer treatments'， 0),
	(121, 'advanced metastatic lung cancer treatment'， 0),
	(122, 'advanced metastatic melanoma treatment'， 0),
	(123, 'advanced metastatic pancreatic cancer treatments'， 0),
	(124, 'advanced metastatic prostate cancer treatment'， 0),
	(125, 'advanced metastatic prostate cancer treatments'， 0),
	(126, 'advanced metastatic skin cancer treatments'， 0),
	(127, 'advanced non small cell lung cancer treatment'， 0),
	(128, 'advanced overactive bladder treatment'， 0),
	(129, 'advanced pancreatic cancer treatments'， 0),
	(130, 'advanced prostate cancer chemotherapy'， 0),
	(131, 'advanced prostate cancer treatemnts'， 0),
	(132, 'advanced prostate cancer treatment'， 0),
	(133, 'advanced prostate cancer treatments'， 0),
	(134, 'advanced renal cell carcinoma treatment'， 0),
	(135, 'advanced skin cancer treatment'， 0),
	(136, 'advances in melanoma treatment'， 0),
	(137, 'affordable cruise packages'， 0),
	(138, 'affordable online master\'s degree'， 0),
	(139, 'affordable senior life insurance'， 0),
	(140, 'afib'， 0),
	(141, 'afib and stroke'， 0),
	(142, 'afib heart condition'， 0),
	(143, 'afib medications'， 0),
	(144, 'afib stoke'， 0),
	(145, 'afib stroke'， 0),
	(146, 'afib stroke medications'， 0),
	(147, 'afib stroke treatment'， 0),
	(148, 'afib stroke treatments'， 0),
	(149, 'afib teatments'， 0),
	(150, 'afib teatments	3	0.43	1.38	4.14	5.3	0.5934'， 0),
	(151, 'afib treatment'， 0),
	(152, 'afib treatment drugs'， 0),
	(153, 'afib treatment guidelines'， 0),
	(154, 'afib treatment options'， 0),
	(155, 'afib treatments'， 0),
	(156, 'aids treatments'， 0),
	(157, 'air condition repair service'， 0),
	(158, 'air conditioning repair houston'， 0),
	(159, 'airritable bowel syndrome abdominal pain'， 0),
	(160, 'alarm for home security'， 0),
	(161, 'alarm home security system'， 0),
	(162, 'alarm home security systems'， 0),
	(163, 'alarm security system for home'， 0),
	(164, 'alcohol abuse help centers'， 0),
	(165, 'alcohol addiction treatment'， 0),
	(166, 'alcohol rehab'， 0),
	(167, 'alcohol rehab facilities'， 0),
	(168, 'alcohol treatment'， 0),
	(169, 'all states insurance'， 0),
	(170, 'allergic eczema'， 0),
	(171, 'allergic reaction'， 0),
	(172, 'allergic reaction treatment'， 0),
	(173, 'allergic rhinitis'， 0),
	(174, 'allergic rhinitis medications'， 0),
	(175, 'allergic rhinitis symptoms'， 0),
	(176, 'allergic rhinitis treatment'， 0),
	(177, 'allergic rhinitis treatments'， 0),
	(178, 'allergic treatment'， 0),
	(179, 'allergies in eyes symptoms'， 0),
	(180, 'allergies medication'， 0),
	(181, 'allergies treatment'， 0),
	(182, 'allergies treatment and prevention'， 0),
	(183, 'allergy'， 0),
	(184, 'allergy and asthma specialists'， 0),
	(185, 'allergy medication'， 0),
	(186, 'allergy medicine'， 0),
	(187, 'allergy meds'， 0),
	(188, 'allergy relief'， 0),
	(189, 'allergy relief medication'， 0),
	(190, 'allergy sinus headache'， 0),
	(191, 'allergy symptom'， 0),
	(192, 'allergy symptoms'， 0),
	(193, 'allergy symptoms and treatment'， 0),
	(194, 'allergy treatment'， 0),
	(195, 'allergy treatments'， 0),
	(196, 'allstate insurance company'， 0),
	(197, 'alternative cancer treatment centers'， 0),
	(198, 'alternative colon cancer treatment centers'， 0),
	(199, 'alternative hiv treatment'， 0),
	(200, 'alternative hiv treatments'， 0),
	(201, 'alternative treatment for multiple myeloma'， 0),
	(202, 'alternative treatment for uterine fibroids'， 0),
	(203, 'alternative treatments sleep apnea'， 0),
	(204, 'alzheimer care'， 0),
	(205, 'anaemia'， 0),
	(206, 'anaemia treatments'， 0),
	(207, 'ancestry dna testing'， 0),
	(208, 'android app development'， 0),
	(209, 'anemia headache relief'， 0),
	(210, 'ankles rheumatoid arthritis treatment'， 0),
	(211, 'ankylosing spondylitis'， 0),
	(212, 'ankylosing spondylitis  treatment'， 0),
	(213, 'ankylosing spondylitis injection treatment'， 0),
	(214, 'ankylosing spondylitis leg pain'， 0),
	(215, 'ankylosing spondylitis medication'， 0),
	(216, 'ankylosing spondylitis medications'， 0),
	(217, 'ankylosing spondylitis medicine'， 0),
	(218, 'ankylosing spondylitis support group online'， 0),
	(219, 'ankylosing spondylitis symptoms'， 0),
	(220, 'ankylosing spondylitis therapy'， 0),
	(221, 'ankylosing spondylitis treatment'， 0),
	(222, 'ankylosing spondylitis treatment options'， 0),
	(223, 'ankylosing spondylitis treatment:'， 0),
	(224, 'ankylosing spondylitis treatments'， 0),
	(225, 'anti aging facial treatment'， 0),
	(226, 'antiretroviral drugs'， 0),
	(227, 'antiviral drugs for hiv'， 0),
	(228, 'antivirus'， 0),
	(229, 'antivirus software'， 0),
	(230, 'antivirus software for business'， 0),
	(231, 'antivirus software small business'， 0),
	(232, 'antivirus+software'， 0),
	(233, 'app development'， 0),
	(234, 'app development software'， 0),
	(235, 'apply credit cards'， 0),
	(236, 'apply fha loan'， 0),
	(237, 'apply for credit card visa'， 0),
	(238, 'apply small business credit card'， 0),
	(239, 'arm pain dvt treatments'， 0),
	(240, 'arm rheumatoid arthritis treatments'， 0),
	(241, 'arms rheumatoid arthritis treatment'， 0),
	(242, 'arthritis'， 0),
	(243, 'arthritis fibromyalgia'， 0),
	(244, 'arthritis hip treatment'， 0),
	(245, 'arthritis knee pain relief'， 0),
	(246, 'arthritis lupus treatment'， 0),
	(247, 'artificial brain'， 0),
	(248, 'artificial intelligence companies'， 0),
	(249, 'asbestos lung cancer'， 0),
	(250, 'asbestosis'， 0),
	(251, 'asset management software'， 0),
	(252, 'associate degree of nursing'， 0),
	(253, 'associates degree nursing online'， 0),
	(254, 'asthma'， 0),
	(255, 'asthma  treatments'， 0),
	(256, 'asthma breathing treatment'， 0),
	(257, 'asthma drug'， 0),
	(258, 'asthma drugs'， 0),
	(259, 'asthma inhalers'， 0),
	(260, 'asthma nebulizer'， 0),
	(261, 'asthma symptoms treatment'， 0),
	(262, 'asthma treatment'， 0),
	(263, 'asthma treatments'， 0),
	(264, 'astigmatism lasik surgery'， 0),
	(265, 'atopic dermatitis'， 0),
	(266, 'atopic dermatitis  treatment'， 0),
	(267, 'atopic dermatitis diagnosis'， 0),
	(268, 'atopic dermatitis eczema'， 0),
	(269, 'atopic dermatitis hand treatment'， 0),
	(270, 'atopic dermatitis hands treatment'， 0),
	(271, 'atopic dermatitis leg treatment'， 0),
	(272, 'atopic dermatitis legs treatment'， 0),
	(273, 'atopic dermatitis medication'， 0),
	(274, 'atopic dermatitis medications'， 0),
	(275, 'atopic dermatitis neck treatment'， 0),
	(276, 'atopic dermatitis relief'， 0),
	(277, 'atopic dermatitis treatment'， 0),
	(278, 'atopic dermatitis treatment options'， 0),
	(279, 'atopic dermatitis treatment options='， 0),
	(280, 'atopic dermatitis treatment='， 0),
	(281, 'atopic dermatitis treatments'， 0),
	(282, 'atopic eczema'， 0),
	(283, 'atrial fibrillation'， 0),
	(284, 'atrial fibrillation and stroke'， 0),
	(285, 'atrial fibrillation medication'， 0),
	(286, 'atrial fibrillation medications'， 0),
	(287, 'atrial fibrillation treatment'， 0),
	(288, 'atrial fibrillation treatments'， 0),
	(289, 'attention deficit disorder treatment'， 0),
	(290, 'attorney bankruptcy'， 0),
	(291, 'autism services'， 0),
	(292, 'autism treatments'， 0),
	(293, 'auto accident lawyer'， 0),
	(294, 'auto loans'， 0),
	(295, 'auto title loans'， 0),
	(296, 'auto title loans online'， 0),
	(297, 'b2b marketing automation software'， 0),
	(298, 'baby cord blood banking cost'， 0),
	(299, 'bachelor degrees online'， 0),
	(300, 'bachelors in early childhood education online accr'， 0),
	(301, 'bachelors in english degree online accredited'， 0),
	(302, 'background check'， 0),
	(303, 'background checks'， 0),
	(304, 'backup'， 0),
	(305, 'backup cloud storage'， 0),
	(306, 'bacterial meningitis'， 0),
	(307, 'bacterial meningitis shot'， 0),
	(308, 'bacterial meningitis vaccinations'， 0),
	(309, 'bacterial meningitis vaccine'， 0),
	(310, 'bacterial meningitis vaccine cost'， 0),
	(311, 'bad credit personal installment loan'， 0),
	(312, 'balance transfer cards no fee'， 0),
	(313, 'balance transfer credit card'， 0),
	(314, 'balance transfer credit card offers'， 0),
	(315, 'balance transfer credit cards'， 0),
	(316, 'balance transfer credit cards no fee'， 0),
	(317, 'balance transfer offers credit cards'， 0),
	(318, 'bankruptcy'， 0),
	(319, 'bankruptcy attorney'， 0),
	(320, 'bankruptcy info'， 0),
	(321, 'bankruptcy lawyer'， 0),
	(322, 'bankruptcy lawyers'， 0),
	(323, 'bankruptcy lawyers near me'， 0),
	(324, 'bankruptcy small business'， 0),
	(325, 'battery repair iphone'， 0),
	(326, 'bed bug bite home remedies'， 0),
	(327, 'bed bug control'， 0),
	(328, 'bed bug exterminator'， 0),
	(329, 'bed bug pest control companies'， 0),
	(330, 'bed bug pest control service'， 0),
	(331, 'bed bug treatment'， 0),
	(332, 'bed bug treatment options'， 0),
	(333, 'bed bug treatments'， 0),
	(334, 'bed bugs exterminator'， 0),
	(335, 'bed bugs exterminators'， 0),
	(336, 'bedbug'， 0),
	(337, 'best 800 number service'， 0),
	(338, 'best 800 number service for small business'， 0),
	(339, 'best acid reflux treatment'， 0),
	(340, 'best airline miles card'， 0),
	(341, 'best alcohol rehab centers'， 0),
	(342, 'best allergy treatment'， 0),
	(343, 'best alzheimer\'s care facilities'， 0),
	(344, 'best balance transfer credit cards'， 0),
	(345, 'best bank account for online business'， 0),
	(346, 'best bed bug exterminators'， 0),
	(347, 'best bed bug treatments'， 0),
	(348, 'best bond mutual funds'， 0),
	(349, 'best business class flights'， 0),
	(350, 'best business credit cards small business'， 0),
	(351, 'best business flights'， 0),
	(352, 'best business phone service provider'， 0),
	(353, 'best business voip service'， 0),
	(354, 'best cable and internet provider'， 0),
	(355, 'best cancer treatment'， 0),
	(356, 'best car loan rates'， 0),
	(357, 'best cash back credit card'， 0),
	(358, 'best cash credit card'， 0),
	(359, 'best cell phone service plans'， 0),
	(360, 'best cheap cell phone plan'， 0),
	(361, 'best cheap phone plans'， 0),
	(362, 'best cheap phone service'， 0),
	(363, 'best cholesterol lowering medication'， 0),
	(364, 'best copd treatment'， 0),
	(365, 'best corporate travel agency'， 0),
	(366, 'best credit card balance transfer'， 0),
	(367, 'best credit card rewards'， 0),
	(368, 'best credit card transfer balance'， 0),
	(369, 'best crm software'， 0),
	(370, 'best crossover deals'， 0),
	(371, 'best crossover lease deals'， 0),
	(372, 'best debt management plan'， 0),
	(373, 'best dental insurance'， 0),
	(374, 'best deodorant body odor'， 0),
	(375, 'best divorce attorney'， 0),
	(376, 'best doctors for lasik eye surgery'， 0),
	(377, 'best drug rehab programs'， 0),
	(378, 'best email marketing software'， 0),
	(379, 'best etf funds'， 0),
	(380, 'best eye laser'， 0),
	(381, 'best free business checking account for small busi'， 0),
	(382, 'best free conference call service'， 0),
	(383, 'best free phone apps'， 0),
	(384, 'best hearing aids'， 0),
	(385, 'best heartburn relief'， 0),
	(386, 'best hedge funds'， 0),
	(387, 'best high interest online savings account'， 0),
	(388, 'best home insurance'， 0),
	(389, 'best home security service'， 0),
	(390, 'best hosted voip for samll business'， 0),
	(391, 'best hosted voip for small business'， 0),
	(392, 'best hosted voip solutions for small business'， 0),
	(393, 'best hybrid suvs'， 0),
	(394, 'best insomnia treatment'， 0),
	(395, 'best interest rates for savers'， 0),
	(396, 'best internet and cable packages'， 0),
	(397, 'best internet and cable provider in my area'， 0),
	(398, 'best internet provider deals'， 0),
	(399, 'best internet service for business'， 0),
	(400, 'best internet service provider'， 0),
	(401, 'best internet tv bundles'， 0),
	(402, 'best ira savings account'， 0),
	(403, 'best ira savings accounts'， 0),
	(404, 'best laser eye surgery'， 0),
	(405, 'best life insurance companies'， 0),
	(406, 'best luxury suvs'， 0),
	(407, 'best mba online'， 0),
	(408, 'best medication psoriatic arthritis'， 0),
	(409, 'best mobile data plan'， 0),
	(410, 'best no contract cell phone'， 0),
	(411, 'best no contract cell phone plans'， 0),
	(412, 'best no contract internet service'， 0),
	(413, 'best online high interest savings'， 0),
	(414, 'best online mba programs'， 0),
	(415, 'best online payment processing service'， 0),
	(416, 'best online payment processing services'， 0),
	(417, 'best online storage'， 0),
	(418, 'best online term life insurance quotes'， 0),
	(419, 'best online universities'， 0),
	(420, 'best pain medication for broken ribs'， 0),
	(421, 'best password manager'， 0),
	(422, 'best payroll service'， 0),
	(423, 'best payroll service for small company'， 0),
	(424, 'best payroll softwares'， 0),
	(425, 'best phone solution for small buisness'， 0),
	(426, 'best phone solution for small business'， 0),
	(427, 'best prepaid cell phone plans'， 0),
	(428, 'best prepaid cell phones plans'， 0),
	(429, 'best rehab centers for depression'， 0),
	(430, 'best repaid phone plans'， 0),
	(431, 'best retirement investments'， 0),
	(432, 'best reverse   mortgage'， 0),
	(433, 'best reverse mortgage'， 0),
	(434, 'best savings rates'， 0),
	(435, 'best sem companies'， 0),
	(436, 'best sleep aid'， 0),
	(437, 'best sleep apnea treatment'， 0),
	(438, 'best sleeping aid'， 0),
	(439, 'best small business checking accounts'， 0),
	(440, 'best small business credit card'， 0),
	(441, 'best small business internet provider'， 0),
	(442, 'best small business payroll service'， 0),
	(443, 'best small business voip service'， 0),
	(444, 'best small suv lease'， 0),
	(445, 'best software for payroll small business'， 0),
	(446, 'best toothache relief'， 0),
	(447, 'best toothpaste for sensitive teeth'， 0),
	(448, 'best travel credit cards'， 0),
	(449, 'best treatment center for pancreatic cancer'， 0),
	(450, 'best treatment for eczema on hands'， 0),
	(451, 'best treatment for stage 4 breast cancera	 stage 4'， 0),
	(452, 'best treatment metastatic breast cancer'， 0),
	(453, 'best unlimited data cell phone plans'， 0),
	(454, 'best video conferencing software small business'， 0),
	(455, 'best website hosting'， 0),
	(456, 'big data'， 0),
	(457, 'big data analytics'， 0),
	(458, 'big data business intelligence'， 0),
	(459, 'big data software'， 0),
	(460, 'big data university'， 0),
	(461, 'binge eating disorder'， 0),
	(462, 'binge eating disorder treatment'， 0),
	(463, 'bipolar disorder'， 0),
	(464, 'bipolar disorder treatment'， 0),
	(465, 'bipolar symptom'， 0),
	(466, 'bis insurance'， 0),
	(467, 'bitcoin day trading software'， 0),
	(468, 'bitcoin online trading'， 0),
	(469, 'bladder cancer'， 0),
	(470, 'bladder cancer alternative treatment'， 0),
	(471, 'bladder cancer prognosis stage 4'， 0),
	(472, 'bladder cancer surgery'， 0),
	(473, 'bladder cancer treatment'， 0),
	(474, 'bladder control'， 0),
	(475, 'bladder control problem'， 0),
	(476, 'bladder control treatment'， 0),
	(477, 'bladder control treatments'， 0),
	(478, 'bladder controls'， 0),
	(479, 'bladder fallen'， 0),
	(480, 'bladder problems'， 0),
	(481, 'bladder prolapse'， 0),
	(482, 'bladder repair surgery'， 0),
	(483, 'bladder%20control'， 0),
	(484, 'bladder+control'， 0),
	(485, 'blood cancers'， 0),
	(486, 'blood clot'， 0),
	(487, 'blood clot disease'， 0),
	(488, 'blood clots'， 0),
	(489, 'blood clots disease'， 0),
	(490, 'blood clots treatment'， 0),
	(491, 'blood cord banking cost'， 0),
	(492, 'blood glucose control'， 0),
	(493, 'blood glucose monitoring'， 0),
	(494, 'blood sugar'， 0),
	(495, 'blood sugar control'， 0),
	(496, 'blood thrombosis'， 0),
	(497, 'blood+sugar'， 0),
	(498, 'blue sapphire engagement rings'， 0),
	(499, 'blue waffle disease'， 0),
	(500, 'blue waffle picture'， 0),
	(501, 'body odor remedies'， 0),
	(502, 'body odor treatments'， 0),
	(503, 'bond funds'， 0),
	(504, 'bone loss treatment'， 0),
	(505, 'bone metastases breast cancer'， 0),
	(506, 'bookings hotels'， 0),
	(507, 'bottled water delivery service'， 0),
	(508, 'brain cancer clinical trials'， 0),
	(509, 'brain cancer treatment'， 0),
	(510, 'brain cancer treatment options'， 0),
	(511, 'brain cancer treatments'， 0),
	(512, 'breast cancer'， 0),
	(513, 'breast cancer stage 4 prognosis'， 0),
	(514, 'breast cancer treatment'， 0),
	(515, 'breast cancer treatment drugs'， 0),
	(516, 'breast cancer treatment optioins'， 0),
	(517, 'breast cancer treatment option'， 0),
	(518, 'breast cancer treatment options'， 0),
	(519, 'breast%20cancer'， 0),
	(520, 'breast+cancer'， 0),
	(521, 'bridge loan'， 0),
	(522, 'broadband deals'， 0),
	(523, 'broadband deals=esrisf'， 0),
	(524, 'bronchitis emphysema pneumonia'， 0),
	(525, 'bsn'， 0),
	(526, 'bsn online nursing programs'， 0),
	(527, 'bug a bug pest extermination'， 0),
	(528, 'buisiness telephone service'， 0),
	(529, 'buisness telephone service'， 0),
	(530, 'burial insurance'， 0),
	(531, 'burial insurance quotes'， 0),
	(532, 'burial+insurance'， 0),
	(533, 'burning eyes'， 0),
	(534, 'burning eyes treatment'， 0),
	(535, 'business 1800 number'， 0),
	(536, 'business 800 phone numbers'， 0),
	(537, 'business account checking'， 0),
	(538, 'business accounting software'， 0),
	(539, 'business airlines'， 0),
	(540, 'business alarm systems'， 0),
	(541, 'business answering service'， 0),
	(542, 'business antivirus'， 0),
	(543, 'business antivirus software'， 0),
	(544, 'business bank account'， 0),
	(545, 'business bank account online'， 0),
	(546, 'business broadband'， 0),
	(547, 'business broadband service'， 0),
	(548, 'business cable'， 0),
	(549, 'business cable internet'， 0),
	(550, 'business cable service'， 0),
	(551, 'business cable services'， 0),
	(552, 'business card printing'， 0),
	(553, 'business cards'， 0),
	(554, 'business cards online'， 0),
	(555, 'business cash advance'， 0),
	(556, 'business cash advance loan'， 0),
	(557, 'business cash advance loans'， 0),
	(558, 'business check'， 0),
	(559, 'business checking account'， 0),
	(560, 'business checking account online'， 0),
	(561, 'business checks'， 0),
	(562, 'business class'， 0),
	(563, 'business class airline tickets'， 0),
	(564, 'business class flight'， 0),
	(565, 'business class flights cheap'， 0),
	(566, 'business class travel'， 0),
	(567, 'business cloud storage solutions'， 0),
	(568, 'business credit card'， 0),
	(569, 'business credit card offers'， 0),
	(570, 'business credit cards'， 0),
	(571, 'business credit cards rewards'， 0),
	(572, 'business credit cards small business'， 0),
	(573, 'business credit line'， 0),
	(574, 'business credit report'， 0),
	(575, 'business credit reports'， 0),
	(576, 'business degree'， 0),
	(577, 'business degrees online'， 0),
	(578, 'business dental insurance'， 0),
	(579, 'business finance loans'， 0),
	(580, 'business firewall hardware'， 0),
	(581, 'business health insurance'， 0),
	(582, 'business health insurance plans'， 0),
	(583, 'business high speed internet'， 0),
	(584, 'business hosted voip'， 0),
	(585, 'business indemnity insurance'， 0),
	(586, 'business intelligence'， 0),
	(587, 'business intelligence software'， 0),
	(588, 'business intelligence software vendors'， 0),
	(589, 'business internet'， 0),
	(590, 'business internet connection'， 0),
	(591, 'business internet phone service'， 0),
	(592, 'business internet plans'， 0),
	(593, 'business internet security'， 0),
	(594, 'business internet service'， 0),
	(595, 'business internet speeds'， 0),
	(596, 'business isp providers'， 0),
	(597, 'business landline deals'， 0),
	(598, 'business liability insurance quotes'， 0),
	(599, 'business line of credit'， 0),
	(600, 'business loan'， 0),
	(601, 'business loans'， 0),
	(602, 'business management online degree programs'， 0),
	(603, 'business marketing degree online'， 0),
	(604, 'business medical insurance'， 0),
	(605, 'business phone and internet'， 0),
	(606, 'business phone service'， 0),
	(607, 'business phone service in my area'， 0),
	(608, 'business phone service provider in my area'， 0),
	(609, 'business phone services'， 0),
	(610, 'business phone systems'， 0),
	(611, 'business phones'， 0),
	(612, 'business phones systems'， 0),
	(613, 'business reporting'， 0),
	(614, 'business telephone service'， 0),
	(615, 'business video conference software'， 0),
	(616, 'business video conferencing'， 0),
	(617, 'business video conferencing software'， 0),
	(618, 'business video conferencing solutions'， 0),
	(619, 'business virus protection'， 0),
	(620, 'business voip'， 0),
	(621, 'business voip phone'， 0),
	(622, 'business voip service providers'， 0),
	(623, 'business voip services'， 0),
	(624, 'business voip solutions'， 0),
	(625, 'business wifi'， 0),
	(626, 'business wifi providers'， 0),
	(627, 'business wifi solutions'， 0),
	(628, 'business+insurance'， 0),